image: ubuntu:latest
variables:
  WORK_DIR: ${AtomSkilsTemplate2022}
  BRANCH: ${CI_COMMIT_REF_NAME}
  REPO: https://github.com/templar820/AtomSkilsTemplate2022.git
  SERVER_URL: ${SERVER_URL}
  SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: Production
    url: "$SERVER_URL"
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh root@"$SERVER_URL" 'cd AtomSkilsTemplate2022; git pull; make stop; make build-production; make start-production;'
