version: '3.8'


#x-frontend: &frontend
#  build:
#    context: .
#    dockerfile: _docker/frontend/Dockerfile
#  image: frontend
#  stdin_open: true
#  ports:
#    - ${PORT}:${PORT}
#  volumes:
#    - ./frontend:/frontend
#    - /frontend/node_modules
#  env_file:
#    - .env


services:
  nginx:
    restart: unless-stopped
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: _docker/nginx/Dockerfile
      args:
        - ESLINT_NO_DEV_ERRORS=$ESLINT_NO_DEV_ERRORS
        - DISABLE_ESLINT_PLUGIN=$DISABLE_ESLINT_PLUGIN
        - CI=$CI
        - TSC_COMPILE_ON_ERROR=$TSC_COMPILE_ON_ERROR
        - REACT_APP_ENDPOINT_PRODUCTION=$REACT_APP_ENDPOINT_PRODUCTION
        - REACT_APP_SWAGGER_ENDPOINT=$REACT_APP_SWAGGER_ENDPOINT
        - REACT_APP_ADMIN_ENDPOINT_DEVELOP=$REACT_APP_ADMIN_ENDPOINT_DEVELOP
        - REACT_APP_ADMIN_ENDPOINT_PRODUCTION=$REACT_APP_ADMIN_ENDPOINT_PRODUCTION
    env_file:
      - .env

#  frontend:
#    container_name: "frontend"
#    <<: *frontend
#    command: npm run start

