version: '3.8'

volumes:
  db-volume:
  db-es:
    driver: local


#
#x-db_transactions: &db_transactions
#  build:
#    context: .
#    dockerfile: _docker/db_transactions/Dockerfile
#  depends_on:
#    - postgres
#    - backend
#  image: db_transactions
#  volumes:
#    - ./db_transactions:/db_transactions
#    - /db_transactions/node_modules
#    - ./backend/src:/db_transactions/backend/src
#  env_file: .env

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

