version: '3.8'


x-frontend: &frontend
  build:
    context: .
    dockerfile: _docker/frontend/Dockerfile
  image: frontend
  container_name: "frontend"
  volumes:
    - ./frontend:/frontend
    - /frontend/node_modules

services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "${PORT}:${PORT}"
#    depends_on:
#      - frontend:
    volumes:
      - ./frontend/build:/frontend/build
      - ./nginx:/etc/nginx/conf.d
    command: /etc/nginx/conf.d/run_nginx.sh
    env_file:
      - .env

  frontend:
    <<: *frontend
    command: npm run start

