version: '3.8'


x-frontend: &frontend
  build:
    context: .
    dockerfile: _docker/frontend/Dockerfile
  image: frontend
  stdin_open: true
  ports:
    - ${PORT}:${PORT}
  volumes:
    - ./frontend:/frontend
    - /frontend/node_modules
  env_file:
    - .env


services:
  nginx:
    restart: unless-stopped
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: _docker/nginx/Dockerfile
    env_file:
      - .env

  frontend:
    container_name: "frontend"
    <<: *frontend
    command: npm run start

