version: '3.8'

volumes:
  db-volume:
  db-es:
    driver: local


x-backend: &backend
  build:
    context: .
    dockerfile: _docker/backend/Dockerfile
  image: backend
  container_name: "backend"
  volumes:
    - ./backend:/backend
    - /backend/node_modules
  restart: unless-stopped
  env_file: .env




services:
  backend:
    <<: *backend
    command: npm run start
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
#  db_init:
#    <<: *db_transactions
#    container_name: "db_init"
#    command: npm run start
#  db_clean:
#    <<: *db_transactions
#    container_name: "db_clean"
#    command: npm run clean
#  frontend:
#    <<: *frontend
#    command: npm run build

