version: '3.8'



x-backend: &backend
  build:
    context: .
    dockerfile: _docker/backend/Dockerfile
  image: backend
  volumes:
    - ./backend:/backend
    - /backend/node_modules
  depends_on:
    - pghost
  restart: unless-stopped
  env_file: .env



services:
  backend:
    container_name: "backend"
    <<: *backend
    command: npm run start
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

